server {
    # Listen on port 80 (the default port we exposed in the Dockerfile)
    listen 80;
    server_name localhost;

    # Where Nginx will look for the files we copied from the builder stage
    root /usr/share/nginx/html;
    index index.html;

   # If the user navigates to /delivery, Nginx will check:
    #   - Does a file named 'delivery' exist? ($uri)
    #   - Does a folder named 'delivery/' exist? ($uri/)
    #   - If neither exist, serve 'index.html' and let React Router handle it.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Vite hashes these filenames, so they never change. We can tell the browser 
    # to cache them for a full year to drastically speed up load times.
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # NEVER CACHE INDEX.HTML
    # Because index.html tells the browser which hashed JS files to download,
    # we NEVER want to cache it. This ensures that when you deploy a new version 
    # of my dashboard, users instantly see the updates instead of a stale version.
    location = /index.html {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
